### ISSUE TITLE
Define App Data

### ISSUE THREAD

**Issue by justinmc** [Autodesk/molecular-simulation-tools#205]
We should define an app data format that will be used for describing the UI that the frontend will generate (see https://github.com/Autodesk/molecular-design-applications/issues/204).

**Comment by justinmc** [comment]
Thinking out loud, here's an MVP way we could do this:

  * Workflows are the top-level data structure as they are now.
  * Workflows have at least one WorkflowNode.  Each one corresponds to a possible "step" that you see numbered on the left side of the app right now.
    - WorkflowNodes are hardcoded into the app.
    - Each has a unique string id (basically a name)
    - Workflows have a `workflowNodeIds` field that is an array of strings.
  * The UI is generated based on these workflowNodes.
  * Data from the user and from the server that corresponds to each workflowNode is set on the `inputs` array, as it is today.
  * The final submit step is also a workflowNode itself?

**Comment by justinmc** [comment]
One step above MVP: If we need to do any configuration on workflowNodes, maybe the `workflowNodeIds` array could instead of just ids be objects with an `id` parameter and some configuration parameters.

**Comment by joseph-schaeffer** [comment]
I like this setup, but "Workflows" is a pretty overloaded term, and the way I see you using them here are as application steps rather than specific computational workflows. If we could come up with another term (much like front-end app steps are now "Widgets") to keep it from colliding with the computational workflow, that would be great.

**Comment by joseph-schaeffer** [comment]
Hit submit too soon. Other than the comment above, I think the steps you've described make sense for the app setup and definition, with one possible exception - I heard at least one requirement for a step that doesn't show up, but does invoke some computation (front-end widget, or back-end workflow). I believe that's being used for input validation/manipulation in some of the current apps.

**Comment by justinmc** [comment]
I agree!  These "workflowNodes" might not even have any backend computation in some cases.  Hopefully we can nail down the nomenclature a bit tomorrow.

I'll bring up the "invisible" steps thing tomorrow as well and make sure that our solution can do that.  Thanks for taking the time to look at this.

**Comment by dionjwa** [comment]
I agree with Joseph in that we need to agree on the terminology. Front end 'widgets' or  'components' or whatever you want to call them should not be called workflows. They do not obey some important assumptions implied with the term 'workflow'.

**Comment by dionjwa** [comment]
Also, I do not think that front-end widgets should be implicitly connected, I think it should be explicit. Implicit wiring up (where you assume the outputs from one 'node' are acceptable and can be connected to a downstream 'node') creates restrictions that not only limit what apps users can create, but also have to be documented (rather than just documenting how to connect widgets).

**Comment by justinmc** [comment]
@dionjwa I like that.  Right now there's not very much structure to the inputs array, so it's hard for the app to know if a step has succeeded in adding some valid input to it without hardcoding stuff for each step.  A standard format would help a lot.

**Comment by justinmc** [comment]
app.yml notes from meeting just now:

```
{
  id: 'SELECTION',
  config: {
    title: 'Ligand Selection',
  },
  url: <url to backend workflow definition>,
  inputs: {
    ligandAtomIds: SELECTION.atomIds,
  },
}
```

**Comment by dionjwa** [comment]
Here's my attempt at putting the QM/MM app in the proposed app json. I decided to do QM/MM instead of VDE because I wanted to capture the user-driven selection aspect:

```
{
	"version": "0.1-alpha",
	"app": {
		"config": {},
		"meta": {
			"name": "QM/MM binding site refinement",
			"version": "0.0.1",
			"git": "https://github.com/Autodesk/molecular-simulation-tools",
			"authors": []
		},
		"widgets": [
			{
				"id": "PDB-Load-Button",
				"bionano-widget-id": "bionano.PDB_LOAD_BUTTON",
				"meta": {},
				"config": {
					"color":"white"
				},
				"out": [
					{
						"name": "PDB_DATA",
						"COMMENT": "In the future, a 'type' declaration can go here"
					}
				]
			},
			{
				"id": "PDB-Validate",
				"bionano-widget-id": "bionano.QMMM_PDB_VALIDATE",
				"in": [
					{ "name": "PDB_DATA" }
				],
				"out": [
					{ "name": "prep.json" },
					{ "name": "prep.pdb" },
					{ "name": "workflow_state.dill" }
				]
			},
			{
				"id": "PDB-Ligand-Selection",
				"bionano-widget-id": "bionano.BIONANO_MOLVIEWER",
				"config": {
					"headless": true,
					"config3d": { "noSplash": true },
					"configViews": {
						"hideHeader": true,
						"hideBrowser": true,
						"hideInspector": true
					}
				},
				"in": [
					{ "name": "PDB_DATA" }
				],
				"out": [
					{ "name": "selection.json" }
				]
			},
			{
				"id": "QMMM binding calculation",
				"bionano-widget-id": "bionano.CWL",
				"config": {
					"git": "git url containing CWL workflow",
					"sha": "git sha",
					"cwl": "relative path in the git repo to the CWL file",
					"input": "CWL input file",
					"inputs": [
						"workflow_state.dill"
					]
				},
				"in": [
					{ "name": "workflow_state.dill" },
					{ "name": "selection.json" }
				],
				"out": [
					{ "name": "final_structure.pdb" },
					{ "name": "results.json" },
					{ "name": "minstep.*.pdb" },
					{ "name": "minsteps.tar.gz" },
					{ "name": "minstep_frames.json" },
				]
			},
			{
				"id": "PDB-QM/MM Results",
				"bionano-widget-id": "bionano.QMMM-RESULTS",
				"config": {
					"headless": true,
					"config3d": { "noSplash": true },
					"configViews": {
						"hideHeader": true,
						"hideBrowser": true,
						"hideInspector": true
					}
				},
				"in": [
					{ "name": "PDB_DATA" },
					{ "name": "minstep_frames.json" },
					{ "name": "results.json" }
				]
			}
		],
		"pipes": [
			{
				"from": ["PDB-Load-Button", "PDB_DATA"],
				"to": ["PDB-Validate", "PDB_DATA"]
			},
			{
				"from": ["PDB-Validate", "selection.json"],
				"to": ["QMMM binding calculation", "selection.json"]
			},
			{
				"from": ["PDB-Validate", "workflow_state.dill"],
				"to": ["QMMM binding calculation", "workflow_state.dill"]
			},
			{
				"from": ["QMMM binding calculation", "final_structure.pdb"],
				"to": ["PDB-QM/MM Results", "PDB_DATA"]
			},
			{
				"from": ["QMMM binding calculation", "minstep_frames.json"],
				"to": ["PDB-QM/MM Results", "minstep_frames.json"]
			},
			{
				"from": ["QMMM binding calculation", "results.json"],
				"to": ["PDB-QM/MM Results", "results.json"]
			}
		]
	}
}
```

Notes: 

 - Note the place where we can add typing in the future.
 - Widgets have an app-scope unique "id", but also a widget id (that we will use to actually create the app), this corresponds roughly to a 'class'. You can have more than one 'instance' of a widget, e.g. multiple versions of the viewer, or  more than one CWL workflow.
 - I tried to keep pipes simple, just use a two-piece array rather than being super explicit e.g. this seemed unnecessarily verbose, OTOH its more explicit and self-documenting:

```{
	"from": {
		"widget": "QMMM binding calculation"
		"pipe": "results.json"
	}
	"to": {
		"widget": "PDB-QM/MM Results"
		"pipe": "results.json"
	}
}```

**Comment by joseph-schaeffer** [comment]
Looks pretty good to me. Some comments:

- I think each widget definition needs a version reference, in addition to the bionano-widget-id. This could be 'latest', or specific pinning info, but it probably should be in there.
- "bionano-widget-id" works as a name for now, but if there are plans to allow widget creation by people other than us, we should probably use a different name. "widget-class-id" maybe? That may be a better name in general anyways, as it more accurately describes what the field is.
- I'm ok with the pipes being the simpler form with arrays; I do think it's not quite as explicit/self-documenting, but it's also really straightforward and I think the tradeoff is a small one.
- I like the "COMMENT" field - those should be allowable in any locations in the JSON explicitly so that the app creator can explain what/why/how they did things a particular way.  One of my biggest complaints with json is the lack of an explicit comment, so adding a field name that's always expected to be used for such and otherwise ignored might really help.
- The "QMMM binging calculation" widget produced some outputs that included a wildcard. Can you go into detail as to how that's handled? Is that just the pipe naming, or is that the actual file(s) that  it would produce? Would those get split (can they be split) when sent to another widget? The use case here ignores two of the outputs, so it's not clear how it should be working. I'm assuming the frames aren't needed for the results widget (because it's not showing animation yet?). Or does the frames json somehow communicate the frame data as well?

**Comment by dionjwa** [comment]
- Absolutely yes on versioning. I missed that aspect. Added.
 - Yes "bionano-widget-id" is sort of a placeholder. If we allow other people to create widgets, I think there will be a bit more of a re-think, since there are some unanswered questions there. I'm trying to be a bit obvious which parts are placeholders. But "widget-class-id" is probably better. Changed.
 - Ok on the pipes.
 - I agree. I think using YAML is better in this regard for comments, and I think it's a bit more readable. There's basically zero overhead of supporting both yaml and json. 
 - I propose that pipes can have wildcard expressions on inputs/outputs, and the underlying infrastructure sends data appropriately. The receiving widget would get the inputs in specific channels still. I may have missed adding some QMMM outputs, that's simply an oversight.

**Comment by dionjwa** [comment]
Also, if there is no version, then assume to use the latest version of that widget.

**Comment by justinmc** [comment]
I think overall this looks really good, and I can get started implementing most of these ideas right now.  No big complaints from me.

Do we expect users will be writing these files by hand, or will this be exclusively generated by a UI we'll write for building apps?

Good point that`widget-class-id` could need to be a lot more complicated when we start supporting interchangeable frontend widgets.  There are a few other parameters in here that might take awhile before we're actually able to take advantage them, but I think this is good to support everything that we're planning.

Also I want to bring @avirshup in and ask: What are the main pieces functionality that an app developer would need, and are they supported by this format?

**Comment by joseph-schaeffer** [comment]
Meeting summary (3/21/2017) on the above topics:

For the short term, we are going ahead with the widget-based definition above, where each widget is displayed as an individual step in the UI. This is for meeting the immediate milestone goals this week. This means that e.g. the QMMM app above written in the new app framework will now show as 5 steps in the short term. This doesn't quite meet the eventual simplicity required, but is a good first step on the path to making the user experience as short as @MalteTinnus is looking for, and is achievable in the current timeframe.

Updates to the spec above, including some things we discussed (wrapping pipes into the widget in: definitions), naming changes, etc, will be handled by @dionjwa.

In the longer term, we discussed having a 'layout' definition in the app specification, which would allow things like are currently displayed in the QMMM app - bundling of a load PDB step and interface with the validation step, so it only shows as a single item rather than separate pieces. There was a lot of discussion as to how to specify this, as well as how we might implement. One point of discussion was whether UI elements are a separate 1st class object that can be re-used or hooked up to by different widgets / widget groups, or whether they are directly associated with a widget and the 'layout' just controls how they are arranged or used. The short term idea is that since one is a superset of the other, we will go with the simpler version (directly associated with a widget) and expand as needed to fit the user requirements - key places it might need the expanded version are results displays (which have their own bag of issues) as well as validation steps (though these may be handleable by error condition logic).  Dion will be fleshing out the first pass at this extended specification.

I am scheduling a meeting later this week to discuss the extended spec issues, but we won't start working on any implementation until after the milestone is completed.  @justinmc is continuing with implementation for dynamic apps, using the every widget is a step specification.

**Comment by joseph-schaeffer** [comment]
@avirshup, @florencio-mazzoldi: see above.
@dionjwa, @justinmc: Is there anything I missed that should be recapped in the summary?

**Comment by avirshup** [comment]
Thanks guys, this looks great! After talking to developers here, a few responses/notes:

 1. It should be easy to create a _simple_ app, especially one that is just `read input -> run backend simulation -> show results`. A simple fill-in-the-blanks app template would be fine.
 2. Developers should be encouraged to spend time polishing their **workflows**. They shouldn't spend a ton of time developing thinking about UI design (at least, not without a professional designer in the room). So, I actually don't want to offer too much power or flexibility for customizing widget UI. 
 3. Similarly, I don't see a need to support any widgets we haven't created ourselves. If an app needs new widgets, we can build them ourselves (for now).

**Comment by joseph-schaeffer** [comment]
@avirshup: Useful feedback. One question I have is whether that point 1 includes things like "read input" -> "verify input is good" -> "run backend" -> "show results". That's been one of the sticking points between a simple version and a more complex one.

**Comment by avirshup** [comment]
@joseph-schaeffer - very good point!!

Sketched out an app with some potential developers today, and it turned out that their "verify input is good" step is actually quite complicated. From the scientific developer perspective, it's just as complex and integral to the simulation as all the other backend steps. Will poke a little more tomorrow.

**Comment by dionjwa** [comment]
@avirshup The last step is the one I have trouble with. Read input OK. Run workflow, Ok because you'll be able to run any CCC/CWL workflow/job, so lots of flexibility there. But 'Show results'? Wouldn't that vary immensely on what exactly the results are, which is likely very different between researchers, even in similar fields? For example, are we expected to create a widget that somehow creates a graph of the results in e.g. D3? Attempting to create a generic 'configurable' results widget is probably really really hard and probably of limited use.

**Comment by avirshup** [comment]
@dionjwa - Here's my current reckoning: a molecule viewer + a few numbers covers about 50% of use cases right off the bat. Adding simple scatterplot to that would cover another 20%, and something like [molecular spreadsheets](http://molsoft.com/gui/chemical_spreadsheet2s.png) are probably the next 10%.

So far, this is holding up, but we'll definitely be holding developers' hands going forward to see if this is correct.
